### PR TITLE
Update dependencies + add incremental annotation processing support

### LINKED ISSUE #38: Any chance of this annotation processor being updated to be incremental?
Now that Realm's annotation processors are incremental (https://github.com/realm/realm-java/pull/6496), can this also be incremental?

### PR DESCRIPTION
**Pull request by Zhuinden**
Fixes https://github.com/cmelchior/realmfieldnameshelper/issues/38 if I see it correctly. :+1:

(but I didn't upgrade the version to 1.3.0, you might want to do that if this gets merged)

### CODE REVIEW

**Comment by BoD** [comment]
Sorry to nag, but, any plan to accept this? Incremental annotation processing would greatly benefit people who have slow builds (aka, everybody 😁) 🙏

**Comment by BoD** [comment]
It's christmas day, a wonderful gift would be to merge this - there are no conflicts so all you need is to click the merge button, should take 1 second 😁 

Please?  🙏

**Comment by cmelchior** [comment]
Yup. Should have merged this ages ago. Will do now and update dependencies in another PR.

**Comment by cmelchior** [comment]
@BoD 2.0.0 has been released with this.

**Comment by BoD** [comment]
Thanks a lot!

**Pull request merged**
